/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import Business.Supplier;
import javax.swing.JOptionPane;
/**
 *
 * @author manalisharma
 */
public class UpdatePanel extends javax.swing.JPanel {

    private Product product;
    /**
     * Creates new form updatePanel
     */
    
    public UpdatePanel(Product product) {
        
        initComponents();
        this.product=product;
        display(product);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void display(Product product){
        
        String SupplierName=product.supplierObject.getSupplierName();
        supplierNameTextfield.setText(SupplierName);
        
        String SupplierPrice=product.supplierObject.getSupplierPrice();
        supplierPriceTextfield.setText(SupplierPrice);
        
        String productName=product.getName();
        nameTextField.setText(productName);
        
        String productPrice=product.getPrice();
        priceTextField.setText(productPrice);
        
        String productDescription=product.getDescription();
        descriptionTextField.setText(productDescription);
        
        String productAvailNum=product.getAvailNum();
        availNumTextField.setText(productAvailNum);
    
        
    
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        availNumTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        EditButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        supplierName = new javax.swing.JLabel();
        supplierPrice = new javax.swing.JLabel();
        supplierPriceTextfield = new javax.swing.JTextField();
        supplierNameTextfield = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 67, 213, -1));

        jLabel3.setText("Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 113, 213, -1));

        availNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTextFieldActionPerformed(evt);
            }
        });
        add(availNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 159, 213, -1));

        jLabel4.setText("Availabity Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        jLabel5.setText("Description:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });
        add(descriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 205, 213, -1));

        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 460, -1, -1));

        jLabel1.setText("Supplier Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 265, -1, -1));

        supplierName.setText("Name:");
        add(supplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 299, -1, -1));

        supplierPrice.setText("Price:");
        add(supplierPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 345, -1, -1));

        supplierPriceTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierPriceTextfieldActionPerformed(evt);
            }
        });
        add(supplierPriceTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 339, 213, -1));

        supplierNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTextfieldActionPerformed(evt);
            }
        });
        add(supplierNameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 293, 213, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void availNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTextFieldActionPerformed

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        product.setName(nameTextField.getText());
        product.setPrice(priceTextField.getText());
        product.setDescription(descriptionTextField.getText());
        product.setAvailNum(availNumTextField.getText());
        product.supplierObject.setSupplierName(supplierNameTextfield.getText());
        product.supplierObject.setSupplierPrice(supplierPriceTextfield.getText());
                
        
       JOptionPane.showMessageDialog(null,"Create Product Successfully");
        
        
    }//GEN-LAST:event_EditButtonActionPerformed

    private void supplierPriceTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierPriceTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierPriceTextfieldActionPerformed

    private void supplierNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTextfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField availNumTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel supplierName;
    private javax.swing.JTextField supplierNameTextfield;
    private javax.swing.JLabel supplierPrice;
    private javax.swing.JTextField supplierPriceTextfield;
    // End of variables declaration//GEN-END:variables
}
