/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Product.VitalSign;
import Product.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manalisharma
 */
public class abnormal extends javax.swing.JPanel {

    /**
     * Creates new form abnormal
     */
    private VitalSignHistory vitalhistory;
    double maxBP;
    double minBP;
   

    abnormal(VitalSignHistory vitalhistory, double maxBP, double minBP) {
        initComponents();
        this.vitalhistory=vitalhistory;
    
        this.minBP= minBP;
        this.maxBP=maxBP;
        
       
        populateTable(); 
        
        
         }
    
    public void resettextfield(){
    
        tempTextfield.setText("");      //clearing the textfield after inputting the value in the array list
        bloodPressureTextfield.setText("");
        pulseTextfield.setText("");
        dateTextfield.setText("");
    
    
    }
    
    
    
    public void populateTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblVitalSign.getModel();
        dtm.setRowCount(0); //this will ensure no rows are there in table when view buttonis clicked and new values are incorporated
    
        for(VitalSign vs: vitalhistory.getAbnormallist(maxBP, minBP)) 
            //arraylist is of type VitalSign so each object of array list will be attribute to the vital sign class and vitalhistory is array
        {
            Object row[]=new Object[2];   //because we want two columns in the table
            row[0]=vs;     
            //this will give us the value of the memory location where vs object is created 
            //also this is how we are binding the object with the table at position 0
            row[1]=vs.getBloodPressure();
            dtm.addRow(row);
        
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSign = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        View1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tempTextfield = new javax.swing.JTextField();
        bloodPressureTextfield = new javax.swing.JTextField();
        pulseTextfield = new javax.swing.JTextField();
        dateTextfield = new javax.swing.JTextField();

        tblVitalSign.setBackground(new java.awt.Color(204, 204, 204));
        tblVitalSign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVitalSign.setGridColor(new java.awt.Color(204, 204, 204));
        tblVitalSign.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblVitalSign);

        jLabel1.setText("View Vital Sign");

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        View1.setText("View");
        View1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Temperature:");

        jLabel3.setText("Blood Pressure:");

        jLabel4.setText("Pulse:");

        jLabel5.setText("Date:");

        tempTextfield.setEditable(false);
        tempTextfield.setBackground(new java.awt.Color(204, 204, 204));
        tempTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTextfieldActionPerformed(evt);
            }
        });

        bloodPressureTextfield.setEditable(false);
        bloodPressureTextfield.setBackground(new java.awt.Color(204, 204, 204));

        pulseTextfield.setEditable(false);
        pulseTextfield.setBackground(new java.awt.Color(204, 204, 204));

        dateTextfield.setEditable(false);
        dateTextfield.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pulseTextfield)
                            .addComponent(tempTextfield)
                            .addComponent(bloodPressureTextfield)
                            .addComponent(dateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(View1))
                    .addComponent(jLabel1))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(View1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodPressureTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulseTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:

        int selectedrow=tblVitalSign.getSelectedRow();

        if(selectedrow>=0){
            int dialogRes=JOptionPane.showConfirmDialog(null, "Selected row is deleted from the table");
            if(dialogRes == JOptionPane.YES_OPTION){

                VitalSign vs=(VitalSign)tblVitalSign.getValueAt(selectedrow,0); //to know which object is selected
                vitalhistory.deleteVital(vs);
                //JOptionPane.showMessageDialog(null,"Selected row is deleted from the table");
                populateTable(); //redisplay the table
                resettextfield();
            }

        }
        else
        JOptionPane.showMessageDialog(null,"Select any row from the table");
    }//GEN-LAST:event_DeleteActionPerformed

    private void View1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View1ActionPerformed
        // TODO add your handling code here:
        //whatever the user is selecting in the table it is showing the object attributes i.e displaying
        int selectedrow=tblVitalSign.getSelectedRow();

        if(selectedrow>=0)

        {

            VitalSign vs=(VitalSign)tblVitalSign.getValueAt(selectedrow,0);//also to know which object user is selecting ,column=0 because we have binded the object overthere so from there itwill be taking the values
            bloodPressureTextfield.setText(String.valueOf(vs.getBloodPressure()));  //Bloodpressure is a double type and we are trying to input it in string so we used stringvalue of
            tempTextfield.setText(String.valueOf(vs.getTemperature()));
            pulseTextfield.setText(String.valueOf(vs.getPulse()));
            dateTextfield.setText(vs.getDate());//date is a string type

        }
        else
        JOptionPane.showMessageDialog(null,"Select any row from the table");

    }//GEN-LAST:event_View1ActionPerformed

    private void tempTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTextfieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tempTextfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton View1;
    private javax.swing.JTextField bloodPressureTextfield;
    private javax.swing.JTextField dateTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pulseTextfield;
    private javax.swing.JTable tblVitalSign;
    private javax.swing.JTextField tempTextfield;
    // End of variables declaration//GEN-END:variables
}
