/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Product.VitalSignHistory;
import Product.VitalSign;
import javax.swing.JOptionPane;
/**
 *
 * @author manalisharma
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    private VitalSignHistory vitalhistory;
    
    public CreatePanel(VitalSignHistory vitalhistory) {
         initComponents();
         this.vitalhistory=vitalhistory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sAVE = new javax.swing.JButton();
        tempTextfield = new javax.swing.JTextField();
        bloodPressureTextfield = new javax.swing.JTextField();
        pulseTextfield = new javax.swing.JTextField();
        dateTextfield = new javax.swing.JTextField();
        show_validation_here = new javax.swing.JLabel();
        show_validation_here1 = new javax.swing.JLabel();
        show_validation_here2 = new javax.swing.JLabel();
        show_validation_here3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setForeground(java.awt.Color.red);

        jLabel1.setText("Temperature:");

        jLabel2.setText("Blood Pressure:");

        jLabel3.setText("Pulse:");

        jLabel4.setText("Date:");

        jLabel5.setText("Create Vital Sign");

        sAVE.setText("SAVE");
        sAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAVEActionPerformed(evt);
            }
        });

        tempTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTextfieldActionPerformed(evt);
            }
        });
        tempTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempTextfieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempTextfieldKeyPressed(evt);
            }
        });

        bloodPressureTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bloodPressureTextfieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bloodPressureTextfieldKeyPressed(evt);
            }
        });

        pulseTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pulseTextfieldKeyTyped(evt);
            }
        });

        dateTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateTextfieldKeyTyped(evt);
            }
        });

        show_validation_here.setForeground(java.awt.Color.red);

        show_validation_here1.setForeground(java.awt.Color.red);

        show_validation_here2.setForeground(java.awt.Color.red);

        show_validation_here3.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(show_validation_here2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sAVE)
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1))
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pulseTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(tempTextfield)
                                            .addComponent(bloodPressureTextfield)
                                            .addComponent(dateTextfield))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(show_validation_here3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(show_validation_here)
                                            .addComponent(show_validation_here1))))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation_here, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bloodPressureTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation_here1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pulseTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation_here2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation_here3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sAVE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAVEActionPerformed
        // TODO add your handling code here:
        
       
            try{
            double Temp= Double.parseDouble(tempTextfield.getText());
            double bp=Double.parseDouble(bloodPressureTextfield.getText());
            int plse=Integer.parseInt(pulseTextfield.getText());
            String dte= dateTextfield.getText();
       
        
        VitalSign v= vitalhistory.addVital();    //making new object for vitalsign and adding it in array
        v.setTemperature(Temp);       
        v.setBloodPressure(bp);
        v.setPulse(plse);
        v.setDate(dte);
        JOptionPane.showMessageDialog(null, "Vital Signs added successfully");
        //creating new object for vital sogn since the attributes be set in other class
        
        tempTextfield.setText("");      //clearing the textfield after inputting the value in the array list
        bloodPressureTextfield.setText("");
        pulseTextfield.setText("");
        dateTextfield.setText("");}
    
        
        catch(Exception e){
          
            
            JOptionPane.showMessageDialog(null, "Please input valid values");  
        }
        
        // take values from text fields into string type variable
        // create separate class name is as or parse
        // if(parse.tryparseInt) is successull then parse and save it in proper type
       // esle show invalid text in lable with red color
    }//GEN-LAST:event_sAVEActionPerformed

    private void tempTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTextfieldActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_tempTextfieldActionPerformed

    private void tempTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempTextfieldKeyPressed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_tempTextfieldKeyPressed

    private void tempTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempTextfieldKeyTyped
        // TODO add your handling code here:
        try{
            
            double Temp= Double.parseDouble(tempTextfield.getText());
            show_validation_here.setText("");
             
        
        }
        catch(Exception e){
            show_validation_here.setText("Invalid");}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_tempTextfieldKeyTyped

    private void bloodPressureTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bloodPressureTextfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPressureTextfieldKeyPressed

    private void bloodPressureTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bloodPressureTextfieldKeyTyped
        // TODO add your handling code here:
        try{
            
            double bp=Double.parseDouble(bloodPressureTextfield.getText());
            show_validation_here1.setText("");
             
        
        }
        catch(Exception e){
            show_validation_here1.setText("Invalid");}
        
    }//GEN-LAST:event_bloodPressureTextfieldKeyTyped

    private void pulseTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pulseTextfieldKeyTyped
        // TODO add your handling code here:
         try{
            
           int plse=Integer.parseInt(pulseTextfield.getText());
            show_validation_here2.setText("");
             
        
        }
        catch(Exception e){
            show_validation_here2.setText("Invalid");}

    }//GEN-LAST:event_pulseTextfieldKeyTyped

    private void dateTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTextfieldKeyTyped
        // TODO add your handling code here:
        
         try{
            
             String dte= dateTextfield.getText();
            show_validation_here3.setText("");
             
        
        }
        catch(Exception e){
            show_validation_here3.setText("Invalid");}
    }//GEN-LAST:event_dateTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureTextfield;
    private javax.swing.JTextField dateTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pulseTextfield;
    private javax.swing.JButton sAVE;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JLabel show_validation_here1;
    private javax.swing.JLabel show_validation_here2;
    private javax.swing.JLabel show_validation_here3;
    private javax.swing.JTextField tempTextfield;
    // End of variables declaration//GEN-END:variables
}
