/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Product.Personal;
import Product.Address;
import javax.swing.JOptionPane;
/**
 *
 * @author manalisharma
 */
public class AddressPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddressPanel
     */
    private Personal personal;
    public AddressPanel(Personal personal) {
        initComponents();
        this.personal=personal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zipcode_label = new javax.swing.JLabel();
        state_label = new javax.swing.JLabel();
        city_label = new javax.swing.JLabel();
        Street_address_label = new javax.swing.JLabel();
        StreetAddressTextfield = new javax.swing.JTextField();
        CityTextfield = new javax.swing.JTextField();
        StateTextfield = new javax.swing.JTextField();
        ZipcodeTextfield = new javax.swing.JTextField();
        Submit2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        zipcode_label.setBackground(new java.awt.Color(153, 153, 153));
        zipcode_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zipcode_label.setText("Zip Code:");

        state_label.setBackground(new java.awt.Color(153, 153, 153));
        state_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        state_label.setText("State:");

        city_label.setBackground(new java.awt.Color(153, 153, 153));
        city_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city_label.setText("City:");

        Street_address_label.setBackground(new java.awt.Color(153, 153, 153));
        Street_address_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Street_address_label.setText("Street Address:");

        StreetAddressTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetAddressTextfieldActionPerformed(evt);
            }
        });

        CityTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextfieldActionPerformed(evt);
            }
        });

        StateTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateTextfieldActionPerformed(evt);
            }
        });

        Submit2.setText("Submit");
        Submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ZipcodeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StreetAddressTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(378, 378, 378))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(Submit2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(zipcode_label, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(state_label, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Street_address_label, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(city_label, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(42, 851, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(StreetAddressTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CityTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ZipcodeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Submit2)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(Street_address_label)
                    .addGap(18, 18, 18)
                    .addComponent(city_label)
                    .addGap(18, 18, 18)
                    .addComponent(state_label)
                    .addGap(18, 18, 18)
                    .addComponent(zipcode_label)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StreetAddressTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetAddressTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetAddressTextfieldActionPerformed

    private void CityTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextfieldActionPerformed

    private void StateTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateTextfieldActionPerformed

    private void Submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2ActionPerformed
        // TODO add your handling code here:
        personal.AddressObject.setStreetAddress(StreetAddressTextfield.getText());
        personal.AddressObject.setState(StateTextfield.getText());
        personal.AddressObject.setCity(CityTextfield.getText());
        personal.AddressObject.setZipCode(ZipcodeTextfield.getText());
        
        JOptionPane.showMessageDialog(null,"Create Addtress Information successfully","warning",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_Submit2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CityTextfield;
    private javax.swing.JTextField StateTextfield;
    private javax.swing.JTextField StreetAddressTextfield;
    private javax.swing.JLabel Street_address_label;
    private javax.swing.JButton Submit2;
    private javax.swing.JTextField ZipcodeTextfield;
    private javax.swing.JLabel city_label;
    private javax.swing.JLabel state_label;
    private javax.swing.JLabel zipcode_label;
    // End of variables declaration//GEN-END:variables
}
