/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Product.Demo;
import Product.AccountInfo;
import Product.Address;
import Product.MedicalRecord;
import Product.License;
import Product.Personal;
/**
 *
 * @author manalisharma
 */
public class ApplicationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReportFrame
     */
    private Demo person;
    private Address address;
    private AccountInfo account;
    private License license;
    private MedicalRecord medical;
    private Personal personal;
    
    
     
    public ApplicationFrame() {
        initComponents();
        person=new Demo();
        address=new Address();
        account=new AccountInfo();
        license=new License();
        medical=new MedicalRecord();
        personal=new Personal();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Application = new javax.swing.JToolBar();
        applicationLabel = new javax.swing.JLabel();
        splitpane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DemoGraph = new javax.swing.JButton();
        AccountInfo = new javax.swing.JButton();
        Address1 = new javax.swing.JButton();
        LicenseInfo = new javax.swing.JButton();
        MedicalRecord = new javax.swing.JButton();
        Report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        Application.setBackground(new java.awt.Color(0, 0, 0));
        Application.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Application.setForeground(new java.awt.Color(255, 255, 255));
        Application.setRollover(true);

        applicationLabel.setForeground(new java.awt.Color(255, 255, 255));
        applicationLabel.setText("Application ");
        Application.add(applicationLabel);

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );

        splitpane.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        DemoGraph.setBackground(new java.awt.Color(255, 255, 255));
        DemoGraph.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DemoGraph.setText("Demographic Information");
        DemoGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoGraphActionPerformed(evt);
            }
        });

        AccountInfo.setBackground(new java.awt.Color(255, 255, 255));
        AccountInfo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        AccountInfo.setText("Account Information");
        AccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfoActionPerformed(evt);
            }
        });

        Address1.setBackground(new java.awt.Color(255, 255, 255));
        Address1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Address1.setText("Address");
        Address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address1ActionPerformed(evt);
            }
        });

        LicenseInfo.setBackground(new java.awt.Color(255, 255, 255));
        LicenseInfo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LicenseInfo.setText("License Information");
        LicenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseInfoActionPerformed(evt);
            }
        });

        MedicalRecord.setBackground(new java.awt.Color(255, 255, 255));
        MedicalRecord.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        MedicalRecord.setText("Medical Record");
        MedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalRecordActionPerformed(evt);
            }
        });

        Report.setBackground(new java.awt.Color(255, 255, 255));
        Report.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Report.setText("Report");
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MedicalRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LicenseInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DemoGraph, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccountInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Address1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(Report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(DemoGraph)
                .addGap(8, 8, 8)
                .addComponent(Address1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LicenseInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Report)
                .addContainerGap(712, Short.MAX_VALUE))
        );

        splitpane.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Application, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Application, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemoGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoGraphActionPerformed
        // TODO add your handling code here:
        DemoPanel demoPanel=new DemoPanel(personal);
        splitpane.setRightComponent(demoPanel);
    }//GEN-LAST:event_DemoGraphActionPerformed

    private void AccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfoActionPerformed
        // TODO add your handling code here:
        AccountPanel1 accountPanel=new AccountPanel1(personal);
        splitpane.setRightComponent(accountPanel);
    }//GEN-LAST:event_AccountInfoActionPerformed

    private void Address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address1ActionPerformed
        // TODO add your handling code here:
        AddressPanel addressPanel=new AddressPanel(personal);
        splitpane.setRightComponent(addressPanel);
    }//GEN-LAST:event_Address1ActionPerformed

    private void LicenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseInfoActionPerformed
        // TODO add your handling code here:
        LicenseInfo licenseInfo=new LicenseInfo(personal);
        splitpane.setRightComponent(licenseInfo);
        
    }//GEN-LAST:event_LicenseInfoActionPerformed

    private void MedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalRecordActionPerformed
        // TODO add your handling code here:
        MedicalPanel medicalPanel=new MedicalPanel(personal);
        splitpane.setRightComponent(medicalPanel);
    }//GEN-LAST:event_MedicalRecordActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
        FinalReport report =new FinalReport(personal);
        splitpane.setRightComponent(report);
    }//GEN-LAST:event_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountInfo;
    private javax.swing.JButton Address1;
    private javax.swing.JToolBar Application;
    private javax.swing.JButton DemoGraph;
    private javax.swing.JButton LicenseInfo;
    private javax.swing.JButton MedicalRecord;
    private javax.swing.JButton Report;
    private javax.swing.JLabel applicationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitpane;
    // End of variables declaration//GEN-END:variables
}
