/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Product.Demo;
import Product.Address;
import javax.swing.JOptionPane;
import Product.Personal;

/**
 *
 * @author manalisharma
 */
public class DemoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemoPanel
     */
    private Personal personal;
    public DemoPanel(Personal personal) 
    {
        initComponents();
        this.personal=personal;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Firstname_label = new javax.swing.JLabel();
        lastname_label = new javax.swing.JLabel();
        phonenumber_label = new javax.swing.JLabel();
        dateofbirth_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        height_labl = new javax.swing.JLabel();
        weight_label = new javax.swing.JLabel();
        socialsecuritynumber_label = new javax.swing.JLabel();
        FirstNametextfield = new javax.swing.JTextField();
        LastNameTextfield = new javax.swing.JTextField();
        PhoneNumberTextfield = new javax.swing.JTextField();
        ageTextfield = new javax.swing.JTextField();
        heightTextfield = new javax.swing.JTextField();
        weightTextfield = new javax.swing.JTextField();
        personSocialSecurityNumber = new javax.swing.JTextField();
        Submit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateofBirthTextfield = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        Firstname_label.setBackground(new java.awt.Color(153, 153, 153));
        Firstname_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Firstname_label.setText("First Name:");

        lastname_label.setBackground(new java.awt.Color(153, 153, 153));
        lastname_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastname_label.setText("Last Name:");

        phonenumber_label.setBackground(new java.awt.Color(153, 153, 153));
        phonenumber_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonenumber_label.setText("Phone Number:");

        dateofbirth_label.setBackground(new java.awt.Color(153, 153, 153));
        dateofbirth_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateofbirth_label.setText("Date of Birth:");

        age_label.setBackground(new java.awt.Color(153, 153, 153));
        age_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age_label.setText("Age:");

        height_labl.setBackground(new java.awt.Color(153, 153, 153));
        height_labl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        height_labl.setText("Height:");

        weight_label.setBackground(new java.awt.Color(153, 153, 153));
        weight_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weight_label.setText("Weight:");

        socialsecuritynumber_label.setBackground(new java.awt.Color(153, 153, 153));
        socialsecuritynumber_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        socialsecuritynumber_label.setText("Social Security Number:");

        FirstNametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNametextfieldActionPerformed(evt);
            }
        });

        personSocialSecurityNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personSocialSecurityNumberActionPerformed(evt);
            }
        });

        Submit1.setText("Submit");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });

        jLabel1.setText("(MM/DD/YY)");

        jLabel2.setText("(in cms)");

        jLabel3.setText("in lbs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(socialsecuritynumber_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonenumber_label)
                            .addComponent(lastname_label)
                            .addComponent(Firstname_label)
                            .addComponent(age_label)
                            .addComponent(height_labl)
                            .addComponent(weight_label)
                            .addComponent(dateofbirth_label))
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personSocialSecurityNumber)
                            .addComponent(weightTextfield)
                            .addComponent(heightTextfield)
                            .addComponent(FirstNametextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastNameTextfield)
                            .addComponent(PhoneNumberTextfield)
                            .addComponent(dateofBirthTextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(ageTextfield))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(Submit1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Firstname_label))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(age_label)
                    .addComponent(dateofBirthTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateofbirth_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(height_labl)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight_label)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socialsecuritynumber_label))
                .addGap(61, 61, 61)
                .addComponent(Submit1)
                .addContainerGap(630, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNametextfieldActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
        // TODO add your handling code here:
        
        
        personal.PersonObject.setFirstName(FirstNametextfield.getText());
        personal.PersonObject.setLastName(LastNameTextfield.getText());
        personal.PersonObject.setPhoneNumber(PhoneNumberTextfield.getText());
        personal.PersonObject.setDateOfBirth(dateofBirthTextfield.getText());
        personal.PersonObject.setAge(ageTextfield.getText());
        personal.PersonObject.setHeight(heightTextfield.getText());
        personal.PersonObject.setWeight(weightTextfield.getText());
        personal.PersonObject.setSocialSecurityNumber(personSocialSecurityNumber.getText());
        
        
        
        JOptionPane.showMessageDialog(null,"Create Person Successfully","warning",JOptionPane.WARNING_MESSAGE);
  
        
        
    }//GEN-LAST:event_Submit1ActionPerformed

    private void personSocialSecurityNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personSocialSecurityNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personSocialSecurityNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstNametextfield;
    private javax.swing.JLabel Firstname_label;
    private javax.swing.JTextField LastNameTextfield;
    private javax.swing.JTextField PhoneNumberTextfield;
    private javax.swing.JButton Submit1;
    private javax.swing.JTextField ageTextfield;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField dateofBirthTextfield;
    private javax.swing.JLabel dateofbirth_label;
    private javax.swing.JTextField heightTextfield;
    private javax.swing.JLabel height_labl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JTextField personSocialSecurityNumber;
    private javax.swing.JLabel phonenumber_label;
    private javax.swing.JLabel socialsecuritynumber_label;
    private javax.swing.JTextField weightTextfield;
    private javax.swing.JLabel weight_label;
    // End of variables declaration//GEN-END:variables
}
