/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Product.License;
import Product.Personal;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
/**
 *
 * @author manalisharma
 */
public class LicenseInfo extends javax.swing.JPanel {

    /**
     * Creates new form LicenseInfo
     */
    private Personal personal;
    public LicenseInfo(Personal personal) {
        initComponents();
        this.personal=personal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextfield = new javax.swing.JTextField();
        DriverLicenseNumberLabel = new javax.swing.JLabel();
        DateOFIssueLabel = new javax.swing.JLabel();
        DateOFExpirationLabel = new javax.swing.JLabel();
        BloodType = new javax.swing.JLabel();
        UploadPictureLabel = new javax.swing.JLabel();
        LicenseNumberTextfield = new javax.swing.JTextField();
        DateOFIssueTextfield = new javax.swing.JTextField();
        DateOFExpirationTextfield = new javax.swing.JTextField();
        BloodTypeCombo = new javax.swing.JComboBox();
        uploadImage = new javax.swing.JButton();
        ImagePathTextfiled = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        BloodTypeTextfield = new javax.swing.JTextField();

        jTextfield.setText("jTextField1");

        DriverLicenseNumberLabel.setBackground(new java.awt.Color(153, 153, 153));
        DriverLicenseNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DriverLicenseNumberLabel.setText("License Number:");

        DateOFIssueLabel.setBackground(new java.awt.Color(153, 153, 153));
        DateOFIssueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOFIssueLabel.setText("Date of Issue:");

        DateOFExpirationLabel.setBackground(new java.awt.Color(153, 153, 153));
        DateOFExpirationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateOFExpirationLabel.setText("Date of Expiration:");

        BloodType.setBackground(new java.awt.Color(153, 153, 153));
        BloodType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BloodType.setText("Blood Type:");

        UploadPictureLabel.setBackground(new java.awt.Color(153, 153, 153));
        UploadPictureLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UploadPictureLabel.setText("Upload Picture:");

        LicenseNumberTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseNumberTextfieldActionPerformed(evt);
            }
        });

        BloodTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "O-", "A", "AB", "B" }));
        BloodTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodTypeComboActionPerformed(evt);
            }
        });

        uploadImage.setText("Upload");
        uploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageActionPerformed(evt);
            }
        });

        ImagePathTextfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagePathTextfiledActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateOFExpirationLabel)
                            .addComponent(UploadPictureLabel)
                            .addComponent(BloodType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ImagePathTextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BloodTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BloodTypeTextfield))
                                .addComponent(DateOFExpirationTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DriverLicenseNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LicenseNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateOFIssueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateOFIssueTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverLicenseNumberLabel)
                    .addComponent(LicenseNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOFIssueLabel)
                    .addComponent(DateOFIssueTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOFExpirationLabel)
                    .addComponent(DateOFExpirationTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BloodType)
                    .addComponent(BloodTypeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadImage)
                    .addComponent(ImagePathTextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadPictureLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LicenseNumberTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseNumberTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseNumberTextfieldActionPerformed

    private void BloodTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodTypeComboActionPerformed
        // TODO add your handling code here:
        BloodTypeTextfield.setText(BloodTypeCombo.getSelectedItem().toString());

    }//GEN-LAST:event_BloodTypeComboActionPerformed

    private void uploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageActionPerformed
        // TODO add your handling code here:
        //Trying to uploafd a file
        JFileChooser fileChooser=new JFileChooser();

        fileChooser.showOpenDialog(this);
        File file=fileChooser.getSelectedFile();
        String path= file.getAbsolutePath();
        ImagePathTextfiled.setText(path);
        personal.LicenseObject.setPicture(path);

        //Trying Image set up using image icon
        
        
    }//GEN-LAST:event_uploadImageActionPerformed

    private void ImagePathTextfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagePathTextfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagePathTextfiledActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        personal.LicenseObject.setLicenseNumber(LicenseNumberTextfield.getText());
        personal.LicenseObject.setDateOFIssue(DateOFIssueTextfield.getText());
        personal.LicenseObject.setDateOFExpiration(DateOFExpirationTextfield.getText());
        //personal.LicenseObject.setPicture(ImagePathTextfiled.getText());
        personal.LicenseObject.setBloodType(jTextfield.getText());
        
        
        JOptionPane.showMessageDialog(null,"Create License Information successfully","warning",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodType;
    private javax.swing.JComboBox BloodTypeCombo;
    private javax.swing.JTextField BloodTypeTextfield;
    private javax.swing.JLabel DateOFExpirationLabel;
    private javax.swing.JTextField DateOFExpirationTextfield;
    private javax.swing.JLabel DateOFIssueLabel;
    private javax.swing.JTextField DateOFIssueTextfield;
    private javax.swing.JLabel DriverLicenseNumberLabel;
    private javax.swing.JTextField ImagePathTextfiled;
    private javax.swing.JTextField LicenseNumberTextfield;
    private javax.swing.JLabel UploadPictureLabel;
    private javax.swing.JTextField jTextfield;
    private javax.swing.JButton submit;
    private javax.swing.JButton uploadImage;
    // End of variables declaration//GEN-END:variables
}
