/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Product.MedicalRecord;
import Product.Personal;
import javax.swing.JOptionPane;

/**
 *
 * @author manalisharma
 */
public class MedicalPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalPanel
     */
    private Personal personal;
    public MedicalPanel(Personal personal) {
        initComponents();
        this.personal=personal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedicalRecordTextfield = new javax.swing.JTextField();
        MedicalRecordNumberLabel = new javax.swing.JLabel();
        Alergy1Label = new javax.swing.JLabel();
        Alergy2Label = new javax.swing.JLabel();
        alergy3Label = new javax.swing.JLabel();
        MedicalRecordTextfield1 = new javax.swing.JTextField();
        Alergy1Textfield = new javax.swing.JTextField();
        Alergy2Textfield = new javax.swing.JTextField();
        Alergy3Textfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        MedicalRecordTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalRecordTextfieldActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(400, 400));

        MedicalRecordNumberLabel.setBackground(new java.awt.Color(153, 153, 153));
        MedicalRecordNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MedicalRecordNumberLabel.setText("Medical Record Number:");

        Alergy1Label.setBackground(new java.awt.Color(153, 153, 153));
        Alergy1Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alergy1Label.setText("Alergy 1:");

        Alergy2Label.setBackground(new java.awt.Color(153, 153, 153));
        Alergy2Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alergy2Label.setText("Alergy 2:");

        alergy3Label.setBackground(new java.awt.Color(153, 153, 153));
        alergy3Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alergy3Label.setText("Alergy 3:");

        MedicalRecordTextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalRecordTextfield1ActionPerformed(evt);
            }
        });

        Alergy1Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy1TextfieldActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedicalRecordNumberLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Alergy1Label)
                                    .addComponent(Alergy2Label)
                                    .addComponent(alergy3Label))
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Alergy2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alergy1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MedicalRecordTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alergy3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButton1)))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalRecordNumberLabel)
                    .addComponent(MedicalRecordTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy1Label)
                    .addComponent(Alergy1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy2Label)
                    .addComponent(Alergy2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alergy3Label)
                    .addComponent(Alergy3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(443, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MedicalRecordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalRecordTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalRecordTextfieldActionPerformed

    private void MedicalRecordTextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalRecordTextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalRecordTextfield1ActionPerformed

    private void Alergy1TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy1TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy1TextfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        personal.MedicalObject.setMedicalRecordNumber(MedicalRecordTextfield.getText());
        personal.MedicalObject.setAlergy1(Alergy1Textfield.getText());
        personal.MedicalObject.setAlergy2(Alergy2Textfield.getText());
        personal.MedicalObject.setAlergy3(Alergy3Textfield.getText());
        
        JOptionPane.showMessageDialog(null,"Create Medical Information Successfully","warning",JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alergy1Label;
    private javax.swing.JTextField Alergy1Textfield;
    private javax.swing.JLabel Alergy2Label;
    private javax.swing.JTextField Alergy2Textfield;
    private javax.swing.JTextField Alergy3Textfield;
    private javax.swing.JLabel MedicalRecordNumberLabel;
    private javax.swing.JTextField MedicalRecordTextfield;
    private javax.swing.JTextField MedicalRecordTextfield1;
    private javax.swing.JLabel alergy3Label;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
