/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliner;


import Business.Airliner;
import Business.AirlinerDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manalisharma
 */
public class CreateAirlinerPanel extends javax.swing.JPanel {

    /**
     * Creates new form createflightPanel
     */
     private AirlinerDirectory airDir;
    private JPanel CreatePanel;
   private  Airliner airliner;


   public CreateAirlinerPanel(JPanel AirlinerPanel, AirlinerDirectory airlinerDirectory) {
         initComponents();
    this.CreatePanel=AirlinerPanel;
    this.airDir=airlinerDirectory;
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlinerLabel = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        capacityTextfield = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        capLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        airlinerLabel.setText("Name:-");

        lblAccNo.setText("Capcity:-");

        nameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyTyped(evt);
            }
        });

        capacityTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                capacityTextfieldKeyTyped(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(204, 204, 204));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        nameLabel.setForeground(java.awt.Color.red);

        capLabel.setForeground(java.awt.Color.red);

        jLabel1.setText("Create Airliner ");

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/manalisharma/Downloads/65179298-stock-vector-airplane-on-blue-background-plane-flying-in-the-sky-front-view-aircraft-flat-style-vector-illustrati.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton)
                .addGap(117, 117, 117)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375))
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airlinerLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAccNo)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacityTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(capLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airlinerLabel)
                            .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacityTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(back))
                .addGap(345, 345, 345))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void resettextfield(){
   
    nameTextfield.setText("");
    capacityTextfield.setText("");
   
    
    
    
    
    
    }
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        
        try{
                if(capacityTextfield.getText().isEmpty()|| nameTextfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "please add all the meta fields"); 
          return ;
        }
            }
                catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "please add fields for price and availabilty");
            return;}
        
        
       
  
           
            
           
            String pname=nameTextfield.getText();
            Double cap=Double.parseDouble(capacityTextfield.getText());
          
           
            
             Airliner airliner=airDir.airlineraddDirectory();
             
            
             airliner.setCapacity(cap);
             airliner.setName(pname);
            
             
            JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            
            resettextfield();
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         CreatePanel.remove(this);
        CardLayout cardlayout=(CardLayout)CreatePanel.getLayout();
        cardlayout.previous(CreatePanel);
       
        Component[] componentArray = CreatePanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirliner manage = (ManageAirliner) component;
        manage.populate();
        CardLayout layout = (CardLayout) CreatePanel.getLayout();
        layout.previous(CreatePanel);
    }//GEN-LAST:event_backActionPerformed

    private void capacityTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capacityTextfieldKeyTyped
        // TODO add your handling code here:
        try{
        Double cap=Double.parseDouble(capacityTextfield.getText());
          capLabel.setText("");
          }
          catch (Exception e){
          capLabel.setText("Invalid");
          }
        
        
        
        
        
        
    }//GEN-LAST:event_capacityTextfieldKeyTyped

    private void nameTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyTyped
        // TODO add your handling code here:
        try{
        String pname=nameTextfield.getText();
          nameLabel.setText("");
          }
          catch (Exception e){
          nameLabel.setText("Invalid");}
    }//GEN-LAST:event_nameTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinerLabel;
    private javax.swing.JButton back;
    private javax.swing.JLabel capLabel;
    private javax.swing.JTextField capacityTextfield;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextfield;
    // End of variables declaration//GEN-END:variables
}
