/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliner;

import Business.Airliner;
import Business.AirlinerDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manalisharma
 */
public class ViewAirlinerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    
    private Airliner airliner;
    private JPanel viewPanel;
    

  

    public ViewAirlinerPanel(Airliner a, JPanel AirlinerPanel) {
          initComponents();
          this.viewPanel = AirlinerPanel;
        this.airliner=a;
         
        nameTextfield.setText(a.getName());
        capacityTextfield.setText(String.valueOf(a.getCapacity()));
        
       
    
    
        
        
        
        }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlinerLabel = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        capacityTextfield = new javax.swing.JTextField();
        nameTextfield = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        capLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.red);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        airlinerLabel.setText("Name:-");
        add(airlinerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 79, -1, -1));

        lblAccNo.setText("Capcity");
        add(lblAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 120, -1, 14));

        capacityTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                capacityTextfieldKeyTyped(evt);
            }
        });
        add(capacityTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 113, 156, -1));

        nameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyTyped(evt);
            }
        });
        add(nameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 73, 156, -1));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 293, -1, -1));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 293, -1, -1));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 293, -1, -1));

        nameLabel.setForeground(java.awt.Color.red);
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 122, 20));

        capLabel.setForeground(java.awt.Color.red);
        add(capLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 122, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        nameTextfield.setEditable(false);
           capacityTextfield.setEditable(false);
     
           
            save.setEnabled(false);
            update.setEnabled(true);
            
           try{
                if(nameTextfield.getText().isEmpty()|| capacityTextfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "please add all the meta fields"); 
          return ;
        }
            }
                catch(Exception e){
           JOptionPane.showMessageDialog(null, "please add fields for price and availabilty");
            return;}
        
            airliner.setName( nameTextfield.getText());
            airliner.setCapacity(Double.parseDouble(capacityTextfield.getText()));
          
            
        
            JOptionPane.showMessageDialog(null, "Airliner updated successfully");        
        
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here: availTextfield.setEditable(true);
            capacityTextfield.setEditable(true);
            
            nameTextfield.setEditable(true);
           
            save.setEnabled(true);
            update.setEnabled(false);
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         viewPanel.remove(this);
        Component[] componentArray = viewPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
       ManageAirliner panel = (ManageAirliner) component;
        //panel.populate();
        CardLayout layout = (CardLayout) viewPanel.getLayout();
        layout.previous(viewPanel);
        
        
    }//GEN-LAST:event_backActionPerformed

    private void nameTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyTyped
        // TODO add your handling code here:
       if (nameTextfield.getText().trim().isEmpty()){
         nameLabel.setText("Invalid");
        
        }
        
        else {
         nameLabel.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_nameTextfieldKeyTyped

    private void capacityTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capacityTextfieldKeyTyped
        // TODO add your handling code here:
        if (capacityTextfield.getText().trim().isEmpty()){
         capLabel.setText("Invalid");
        
        }
        
        else {
         capLabel.setText("");
        }
        
        
        
 
        
    }//GEN-LAST:event_capacityTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinerLabel;
    private javax.swing.JButton back;
    private javax.swing.JLabel capLabel;
    private javax.swing.JTextField capacityTextfield;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
