/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Agency;

import Business.Airliner;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manalisharma
 */
public class ManageTravelAgency extends javax.swing.JPanel {

    /**
     * Creates new form ManageTravelAgency
     */
    private JPanel ManageTravel;
    private TravelAgency travel;
    
   

    public ManageTravelAgency(TravelAgency travel, JPanel cardlayoutjPanel) {
       initComponents();
       this.travel=travel;
       this.ManageTravel=cardlayoutjPanel;
       populate();
    
    
    }

    
     public void populate(){
       int rowCount = travelDirectory.getRowCount();
        DefaultTableModel model = (DefaultTableModel)travelDirectory.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
        
        for(Airliner a: travel.getAirDir().getAirlinerDirectory())
        
        {
             
            Object row[] = new Object[6];
              
            for(Flight b: a.getFlightDirectory().getFlight_Directory()){
          
            row[0]=b.getName();
            row[1]=b.getSeat();
            row[2]=b.getFromDestination();
            row[3]=b.getToDestination();
            row[4]=b.getPrice();
        
        model.addRow(row);
        
            }
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        travelDirectory = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        travelDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Seat", "From", "To", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(travelDirectory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 75, 549, 153));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 284, 100, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 284, 90, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 284, 100, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Create");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 284, 92, -1));

        jLabel1.setText("Manage Travel Agency");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 24, 152, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       CreateTravelAgency createpanel;
        createpanel = new  CreateTravelAgency(ManageTravel, travel);
        ManageTravel.add("CreatePanel",createpanel);
        CardLayout cardlayout=(CardLayout)ManageTravel.getLayout();
     
        cardlayout.next(ManageTravel);
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row=travelDirectory.getSelectedRow();
        if(row<0)
        //that means there is an error and user has not selected any row
        {
            JOptionPane.showMessageDialog(null,"Please make a selection");
            return; }
        
        else{
          TravelAgency travel=(TravelAgency)travelDirectory.getValueAt(row, 0);
          ViewTravelAgency panel=new ViewTravelAgency(travel,ManageTravel);
          CardLayout cardlayout=(CardLayout)ManageTravel.getLayout();
          ManageTravel.add("ViewPanel",panel);
          cardlayout.next(ManageTravel);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = travelDirectory.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
           /*    TravelAgency trave=(TravelAgency)travelDirectory.getValueAt(row, 0);
              travel.getAirDir().deleteAirliner(trave);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }*/
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageTravel.remove(this);
        CardLayout cardlayout=(CardLayout)ManageTravel.getLayout();
        cardlayout.previous(ManageTravel);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable travelDirectory;
    // End of variables declaration//GEN-END:variables
}
