/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageFlights;

import Business.Airliner;
import Business.Flight;
import Business.FlightDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
//import Interface.ManageAgency.ManageFlight;

/**
 *
 * @author manalisharma
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    
    private JPanel CreatePanel;
    Airliner airliner;
    

    
    public CreatePanel(Airliner airliner, JPanel ManageFlight) {
        initComponents();
        this.airliner=airliner;
        this.CreatePanel=ManageFlight;
    
    
    }

        
    
    
    public void resettextfield(){
    
        flightTextfield.setText("");      //clearing the textfield after inputting the value in the array list
        priceTextfield.setText("");
        
        fromDestinationTextfield.setText("");
        scheduleTextfield.setText("");
        todestinationTextfield.setText("");
        //startTextfield.setText("");
        //endTextfield.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availLabel = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        airlinerLabel = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        flightTextfield = new javax.swing.JTextField();
        priceTextfield = new javax.swing.JTextField();
        fromDestinationTextfield = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        To = new javax.swing.JLabel();
        scheduleTextfield = new javax.swing.JTextField();
        To1 = new javax.swing.JLabel();
        todestinationTextfield = new javax.swing.JTextField();
        lblBalance6 = new javax.swing.JLabel();
        lblBalance7 = new javax.swing.JLabel();
        monthcombo = new javax.swing.JComboBox();
        yearcombo = new javax.swing.JComboBox();
        daycombo = new javax.swing.JComboBox();
        monthcombo1 = new javax.swing.JComboBox();
        daycombo1 = new javax.swing.JComboBox();
        yearcombo1 = new javax.swing.JComboBox();
        fLabel = new javax.swing.JLabel();
        pLabel = new javax.swing.JLabel();
        frLabel = new javax.swing.JLabel();
        tLabel = new javax.swing.JLabel();
        tLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        availLabel.setForeground(java.awt.Color.red);
        availLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                availLabelKeyPressed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("Create Flight");
        add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, -1, -1));

        airlinerLabel.setText("Flight Name*");
        add(airlinerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 98, -1, -1));

        lblBankName.setText("Price*");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 144, -1, -1));

        lblBalance.setText("From Destination");
        add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 184, -1, -1));

        flightTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                flightTextfieldKeyTyped(evt);
            }
        });
        add(flightTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 92, 118, -1));

        priceTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTextfieldKeyTyped(evt);
            }
        });
        add(priceTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 138, 118, -1));

        fromDestinationTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fromDestinationTextfieldKeyTyped(evt);
            }
        });
        add(fromDestinationTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 172, 118, -1));

        create.setBackground(new java.awt.Color(204, 204, 204));
        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 394, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 394, 84, -1));

        To.setText("Schedule");
        add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        scheduleTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                scheduleTextfieldKeyTyped(evt);
            }
        });
        add(scheduleTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 244, 118, -1));

        To1.setText("To Destination");
        add(To1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 213, -1, -1));

        todestinationTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                todestinationTextfieldKeyTyped(evt);
            }
        });
        add(todestinationTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 207, 118, -1));

        lblBalance6.setText("Start Date");
        add(lblBalance6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 294, -1, -1));

        lblBalance7.setText("Finish Date");
        add(lblBalance7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 324, -1, -1));

        monthcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "SEept", "Oct", "Nov", "Dec", " " }));
        add(monthcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 284, 60, -1));

        yearcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017", "2018" }));
        add(yearcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 284, 60, -1));

        daycombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(daycombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 284, 60, -1));

        monthcombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "SEept", "Oct", "Nov", "Dec", " " }));
        add(monthcombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 314, 60, -1));

        daycombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(daycombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 314, 60, -1));

        yearcombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017", "2018" }));
        add(yearcombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 314, 60, -1));

        fLabel.setForeground(java.awt.Color.red);
        add(fLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 158, 28));

        pLabel.setForeground(java.awt.Color.red);
        add(pLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 138, 158, 28));

        frLabel.setForeground(java.awt.Color.red);
        add(frLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 172, 158, 28));

        tLabel.setForeground(java.awt.Color.red);
        add(tLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 207, 158, 28));

        tLabel1.setForeground(java.awt.Color.red);
        add(tLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 244, 158, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/manalisharma/Downloads/images.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 260, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void availLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_availLabelKeyPressed

    }//GEN-LAST:event_availLabelKeyPressed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        /*
        
        String format = "dd-MM-yyyy:HH:mm:SS";
            SimpleDateFormat sdf = new SimpleDateFormat(format);

            String startDate= startTextfield.getText();
            String endDate= endTextfield.getText();

            Date flight_startDate = null;
            Date flight_endDate = null;*/
            
            try{
                if(fromDestinationTextfield.getText().isEmpty()|| priceTextfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "please add all the meta fields"); 
          return ;
        }
            }
                catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "please add fields for price and From Destination");
            return;}
        
        try{
            
            
            Flight flight = airliner.getFlightDirectory().addFlight();
            flight.setName(flightTextfield.getText());
            flight.setFromDestination(fromDestinationTextfield.getText());
            flight.setToDestination(todestinationTextfield.getText());
            flight.setSchedule(scheduleTextfield.getText());
            /*flight_startDate = sdf.parse(startDate);
                flight_endDate = sdf.parse(endDate);
                  flight.setStartDate(flight_startDate);
            flight.setEndDate(flight_endDate);*/
            String price = priceTextfield.getText();
            if(price.isEmpty()==false) {
                Double Price=Double.parseDouble(price);
                
                flight.setPrice(Price);
            }
            String string=daycombo.getSelectedItem().toString();
            string = string + " " + monthcombo.getSelectedItem().toString() + " " + yearcombo.getSelectedItem().toString();
            flight.setStartDate(string);
            
            String str=daycombo1.getSelectedItem().toString();
            
            str = str + " " + monthcombo1.getSelectedItem().toString() + " " + yearcombo1.getSelectedItem().toString();
            flight.setEndDate(str);
           
            
            
            
            JOptionPane.showMessageDialog(null, "Flight successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);

            
        
            
            
            
            resettextfield();
        }
              catch(Exception e){
          
            
            JOptionPane.showMessageDialog(null, "Error");  
        }
        
        
    }//GEN-LAST:event_createActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       
     
      
        
        
      
        
        
        CreatePanel.remove(this);
        
        Component[] componentArray = CreatePanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlighstCatalog manage = (ManageFlighstCatalog) component;
        manage.populate();
        CardLayout layout = (CardLayout) CreatePanel.getLayout();
        layout.previous(CreatePanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void flightTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_flightTextfieldKeyTyped
        // TODO add your handling code here:
         if (flightTextfield.getText().trim().isEmpty()){
        fLabel.setText("Invalid");
        
        }
        
        else {
        fLabel.setText("");
        }
        
        
    }//GEN-LAST:event_flightTextfieldKeyTyped

    private void fromDestinationTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromDestinationTextfieldKeyTyped
        // TODO add your handling code here:
          if (fromDestinationTextfield.getText().trim().isEmpty()){
        frLabel.setText("Invalid");
        
        }
        
        else {
        frLabel.setText("");
        }
        
    }//GEN-LAST:event_fromDestinationTextfieldKeyTyped

    private void priceTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextfieldKeyTyped
        // TODO add your handling code here:
          if (priceTextfield.getText().trim().isEmpty()){
        pLabel.setText("Invalid");
        
        }
        
        else {
        pLabel.setText("");
        }
        
    }//GEN-LAST:event_priceTextfieldKeyTyped

    private void todestinationTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_todestinationTextfieldKeyTyped
        // TODO add your handling code here:
          if (todestinationTextfield.getText().trim().isEmpty()){
        tLabel.setText("Invalid");
        
        }
        
        else {
        tLabel.setText("");
        }
        
    }//GEN-LAST:event_todestinationTextfieldKeyTyped

    private void scheduleTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scheduleTextfieldKeyTyped
        // TODO add your handling code here:
          if (scheduleTextfield.getText().trim().isEmpty()){
        tLabel1.setText("Invalid");
        
        }
        
        else {
        tLabel1.setText("");
        }
        
    }//GEN-LAST:event_scheduleTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel To;
    private javax.swing.JLabel To1;
    private javax.swing.JLabel airlinerLabel;
    private javax.swing.JLabel availLabel;
    private javax.swing.JButton create;
    private javax.swing.JComboBox daycombo;
    private javax.swing.JComboBox daycombo1;
    private javax.swing.JLabel fLabel;
    private javax.swing.JTextField flightTextfield;
    private javax.swing.JLabel frLabel;
    private javax.swing.JTextField fromDestinationTextfield;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalance6;
    private javax.swing.JLabel lblBalance7;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblHead;
    private javax.swing.JComboBox monthcombo;
    private javax.swing.JComboBox monthcombo1;
    private javax.swing.JLabel pLabel;
    private javax.swing.JTextField priceTextfield;
    private javax.swing.JTextField scheduleTextfield;
    private javax.swing.JLabel tLabel;
    private javax.swing.JLabel tLabel1;
    private javax.swing.JTextField todestinationTextfield;
    private javax.swing.JComboBox yearcombo;
    private javax.swing.JComboBox yearcombo1;
    // End of variables declaration//GEN-END:variables
}
