/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Boston.Boston;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Disaster;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PoliceEnterprise;
import Business.Organisation.Organisation;
import Business.Organisation.PoliceOrganisation;
import Business.WorkQueue.CustomerToPoliceRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author manalisharma
 */
public class RequestPoliceCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PCreqMessagePanel
     */
    JPanel userProcessContainer;
    Disaster disaster;
    CustomerDirectory cusDir;
    PoliceOrganisation polorg;
    public RequestPoliceCustomerPanel(JPanel userProcessContainer,CustomerDirectory cusDir,Disaster disaster) {
        
        initComponents();
        this.cusDir=cusDir;
        this.userProcessContainer=userProcessContainer;
        this.disaster=disaster;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Message_JLabel = new javax.swing.JLabel();
        Message_JTextfield = new javax.swing.JTextField();
        Submit_JButton = new javax.swing.JButton();
        Back_JButton = new javax.swing.JButton();

        Message_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Message_JLabel.setText("Message");

        Message_JTextfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Message_JTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Message_JTextfieldActionPerformed(evt);
            }
        });

        Submit_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit_JButton.setText("Submit >>");
        Submit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_JButtonActionPerformed(evt);
            }
        });

        Back_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back_JButton.setText("<< Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Submit_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Back_JButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(401, 401, 401)
                            .addComponent(Message_JLabel)
                            .addGap(80, 80, 80)
                            .addComponent(Message_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(588, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Message_JLabel)
                    .addComponent(Message_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Submit_JButton)
                .addContainerGap(541, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Message_JTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Message_JTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Message_JTextfieldActionPerformed

    private void Submit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_JButtonActionPerformed
        // TODO add your handling code here:
        String message = Message_JTextfield.getText();
        CustomerToPoliceRequest request=new CustomerToPoliceRequest();
        request.setMessage(message);
        request.setStatus("Sent");
        for(Customer c:cusDir.getCusDir()){
            String name=c.getName();
        
            request.setSender1(name);}
        
        Organisation org=null;
        for(Boston net1 :disaster.getNetworkList()){
            for(Enterprise enter1:net1.getEnterpriseDirectory().getEnterpriseList()){
                 for(Organisation org1:enter1.getOrganisationDirectory().getOrganisationList()){
                     if(org1 instanceof PoliceOrganisation){
                         polorg=(PoliceOrganisation)org1;
                         polorg.getCtprqueue().add(request);
                         
                     
                     }
                         
                 }
            }
         }
               
        
        
        
        
        if(org!=null){
        for(Boston net :disaster.getNetworkList()){
            for(Enterprise enter:net.getEnterpriseDirectory().getEnterpriseList()){
        
                if(enter instanceof PoliceEnterprise){
                     for(Organisation or:enter.getOrganisationDirectory().getOrganisationList()){
                            if (or instanceof PoliceOrganisation){
                            polorg=(PoliceOrganisation) or;
                            polorg.getCtprqueue().add(request);
                            }
                     }
                }
            }
        }
        }
        
    
    }//GEN-LAST:event_Submit_JButtonActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] componentArray = userProcessContainer.getComponents();
            for(Component c:componentArray){

                if(c instanceof  PoliceCustomerPanel ){
                    PoliceCustomerPanel pthw = (PoliceCustomerPanel) c;
                    pthw.populateTable();
                }
            }
        
        
    }//GEN-LAST:event_Back_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel Message_JLabel;
    private javax.swing.JTextField Message_JTextfield;
    private javax.swing.JButton Submit_JButton;
    // End of variables declaration//GEN-END:variables
}
