/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Disaster;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;


/**
 *
 * @author rusha
 */


public class SignUpJPanel extends javax.swing.JPanel {
private Customer customer;
private CustomerDirectory cusDir;
private JPanel userProcessContainer;
private Disaster disaster;
   
    

    public SignUpJPanel(JPanel userProcessContainer, Disaster disaster, CustomerDirectory cusDir) {
         initComponents();
            this.userProcessContainer=userProcessContainer;
            this.disaster=disaster;
       
        this.cusDir=cusDir; 
        this.disaster=disaster;
  
    }
    
    public void resetTextfield(){
    
    Name_JTextField.setText("");
    number_JTextfield.setText("");
    email_JTextfield.setText("");
    jTextArea1.setText("");

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender_ButtonGroup = new javax.swing.ButtonGroup();
        CivilianWorkArea_JButton = new javax.swing.JButton();
        Title_JLabel = new javax.swing.JLabel();
        Name_JTextField = new javax.swing.JTextField();
        Name_JLabel = new javax.swing.JLabel();
        PhoneNumber_JLabel = new javax.swing.JLabel();
        number_JTextfield = new javax.swing.JTextField();
        EmailAddress_JLabel = new javax.swing.JLabel();
        email_JTextfield = new javax.swing.JTextField();
        Gender_JLabel = new javax.swing.JLabel();
        Address_JLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Male_JRadioButton = new javax.swing.JRadioButton();
        Female_JRadioButton = new javax.swing.JRadioButton();
        Next_JLabel = new javax.swing.JButton();

        CivilianWorkArea_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CivilianWorkArea_JButton.setText("Sign Up >>");
        CivilianWorkArea_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CivilianWorkArea_JButtonActionPerformed(evt);
            }
        });

        Title_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title_JLabel.setText("Sign Up Page");

        Name_JTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_JTextFieldActionPerformed(evt);
            }
        });

        Name_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name_JLabel.setText("Name");

        PhoneNumber_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PhoneNumber_JLabel.setText("Phone Number");

        number_JTextfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        EmailAddress_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmailAddress_JLabel.setText("Email Address");

        email_JTextfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Gender_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Gender_JLabel.setText("Gender");

        Address_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Address_JLabel.setText("Address");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Gender_ButtonGroup.add(Male_JRadioButton);
        Male_JRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Male_JRadioButton.setText("Male");

        Gender_ButtonGroup.add(Female_JRadioButton);
        Female_JRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Female_JRadioButton.setText("Female");

        Next_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Next_JLabel.setText("Next >>");
        Next_JLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_JLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Name_JLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Title_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(PhoneNumber_JLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EmailAddress_JLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CivilianWorkArea_JButton)
                        .addGap(18, 18, 18)
                        .addComponent(Next_JLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address_JLabel)
                            .addComponent(Gender_JLabel))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Female_JRadioButton)
                            .addComponent(Male_JRadioButton))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_JLabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailAddress_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address_JLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender_JLabel)
                    .addComponent(Male_JRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Female_JRadioButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CivilianWorkArea_JButton)
                    .addComponent(Next_JLabel))
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CivilianWorkArea_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CivilianWorkArea_JButtonActionPerformed
        // TODO add your handling code here:
       
        Customer c= cusDir.addCustomer();
        String name=Name_JTextField.getText();
        c.setName(name);
        String number=number_JTextfield.getText();
        c.setPhoneNumber(number);
        String email=email_JTextfield.getText();
        c.setEmail(email);
        
        
        
       
    }//GEN-LAST:event_CivilianWorkArea_JButtonActionPerformed

    private void Name_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_JTextFieldActionPerformed

    private void Next_JLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_JLabelActionPerformed
        // TODO add your handling code here:
         CustomerWorkPanel customerWorkPanel = new CustomerWorkPanel(userProcessContainer, cusDir,disaster);
         //customerWorkPanel.populateTable();
         userProcessContainer.add("customerWorkPanel",customerWorkPanel);
         CardLayout layout=(CardLayout)userProcessContainer.getLayout();
         layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_Next_JLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_JLabel;
    private javax.swing.JButton CivilianWorkArea_JButton;
    private javax.swing.JLabel EmailAddress_JLabel;
    private javax.swing.JRadioButton Female_JRadioButton;
    private javax.swing.ButtonGroup Gender_ButtonGroup;
    private javax.swing.JLabel Gender_JLabel;
    private javax.swing.JRadioButton Male_JRadioButton;
    private javax.swing.JLabel Name_JLabel;
    private javax.swing.JTextField Name_JTextField;
    private javax.swing.JButton Next_JLabel;
    private javax.swing.JLabel PhoneNumber_JLabel;
    private javax.swing.JLabel Title_JLabel;
    private javax.swing.JTextField email_JTextfield;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField number_JTextfield;
    // End of variables declaration//GEN-END:variables
}
