/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import Business.Seat;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manalisharma
 */
public class SeatPanel extends javax.swing.JPanel {

    /**
     * Creates new form bookPanel
     */
   JPanel bookPanel;
   Seat s;
   Customer customer;
    CustomerDirectory cusDir;

    

   /* public SeatPanel(JPanel MasterSchedulePanel, CustomerDirectory cusDir) {
    initComponents();
        this.bookPanel=MasterSchedulePanel;
        this.s=new Seat();
        this.customer=new Customer();
        this.cusDir=new CustomerDirectory();
        booking();   
    
    
    
    
    
    
    }*/
    /*

    public SeatPanel(JPanel TicketPanel, Flight f) {
        this.bookPanel=TicketPanel;
        this.s=new Seat();
        this.customer=new Customer();
        this.cusDir=new CustomerDirectory();
        
        booking();   
    
    
    
    
    
    
    }
*/

    public SeatPanel(JPanel MasterSchedulePanel, CustomerDirectory cusDir, Flight f) {
        initComponents();
        this.bookPanel=MasterSchedulePanel;
        this.s=new Seat();
        this.customer=new Customer();
        this.cusDir=new CustomerDirectory();
        fliTextfield.setText(f.getName());
        priceTextfield.setText(String.valueOf(f.getPrice()));
       fromTextfield.setText(f.getFromDestination());
       toTextfield.setText(f.getToDestination());
        booking(); 
    
    
    
    
    
    }
    
    
    
    public void booking(){
    
    
   
    
   DefaultTableModel model=(DefaultTableModel)seatTable.getModel();
   for(String[] r: s.getSeat()){
       
       model.addRow(r);
  
    
   
   }
   
   
    
    
    
  // String p=(String)seatTable.getModel().getValueAt(row, col);
    
 /*for(int i=0; i<s. ;i++)
    
    { String[] row=new String[seat[i].length];
    
for(int j=0 ;j<seat[i].length;j++){

row[j]=seat[i][j];

}  
model.addRow(seat);
    }
    
  
    */
    }
    
    
    public void resettextfield(){
 
        cNameTextfield.setText("");
        cIDTextfield.setText("");
        seat.setText("");
 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        seatTable = new javax.swing.JTable();
        seat = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fliTextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cIDTextfield = new javax.swing.JTextField();
        cNameTextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priceTextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fromTextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        toTextfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        seatTable.setBackground(new java.awt.Color(204, 204, 204));
        seatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Window", "Middle ", "Aisle", "", "Aisle", "Middle", "Window"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        seatTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seatTable.setGridColor(new java.awt.Color(204, 204, 204));
        seatTable.setRowSelectionAllowed(false);
        seatTable.getTableHeader().setReorderingAllowed(false);
        seatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seatTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(seatTable);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel1.setText("Assigned Seat");

        jLabel2.setText("Flight Name:-");

        jLabel3.setText("Customer Name:");

        jLabel4.setText("Customer ID:");

        cIDTextfield.setEditable(false);

        jLabel5.setText("Price:-");

        jLabel6.setText("From Destination:-");

        jLabel7.setText("To Destination:-");

        toTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextfieldActionPerformed(evt);
            }
        });

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/manalisharma/Downloads/op.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 419, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fliTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                            .addComponent(priceTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fromTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(toTextfield)
                                            .addComponent(seat)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(next)
                        .addGap(289, 289, 289))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fliTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fromTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(toTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(next)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatTableMouseClicked
        // TODO add your handling code here:
       int col=seatTable.getSelectedColumn();
    int row = seatTable.getSelectedRow();
         seat.setText((String) seatTable.getValueAt(row, col));
        
            
            
       
        
        
    }//GEN-LAST:event_seatTableMouseClicked

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        
        BookingFlight panel=new BookingFlight(bookPanel);
        CardLayout cardlayout=(CardLayout)bookPanel.getLayout();
        bookPanel.add("BookingFlight",panel);
        cardlayout.next(bookPanel);
        
        
        /*
        String pname=cNameTextfield.getText();
            
           //int id=Integer.parseInt(cIDTextfield.getText());
         
           
            
            customer=cusDir.addCustomer();
             
            customer.setName(pname);
            
             resettextfield();
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to book this flight?","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION)
            
            {
                
          String seatNumber=seat.getText();
           BookingFlight panel=new BookingFlight(seatNumber ,bookPanel,customer);
          CardLayout cardlayout=(CardLayout)bookPanel.getLayout();
          bookPanel.add("ViewCustomerPanel",panel);
          cardlayout.next(bookPanel);
        
            }
             
            else{
            JOptionPane.showMessageDialog(null, "Seat Not Chosen!");
            }
            
        
        */
        
        
        
        
        
        
        
        
        
        
        
       
    }//GEN-LAST:event_nextActionPerformed

    private void toTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTextfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Congratulations your flight is booked, please proceed for payment");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cIDTextfield;
    private javax.swing.JTextField cNameTextfield;
    private javax.swing.JTextField fliTextfield;
    private javax.swing.JTextField fromTextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton next;
    private javax.swing.JTextField priceTextfield;
    private javax.swing.JTextField seat;
    private javax.swing.JTable seatTable;
    private javax.swing.JTextField toTextfield;
    // End of variables declaration//GEN-END:variables
}
