

package UserInterface.AdminstrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organisation organisation;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organisation organisation) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        Value_JLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_JLabel = new javax.swing.JLabel();
        Enterprise_JLabel = new javax.swing.JLabel();
        Value_JLabel = new javax.swing.JLabel();
        ManageOrganization_JButton = new javax.swing.JButton();
        ManageEmployee_JButton = new javax.swing.JButton();
        ManageUser_JButton = new javax.swing.JButton();

        Title_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title_JLabel.setText("My Work Area -Adminstrative Role");

        Enterprise_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Enterprise_JLabel.setText("EnterPrise :");

        Value_JLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Value_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Value_JLabel.setText("<value>");

        ManageOrganization_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageOrganization_JButton.setText("Manage Organization");
        ManageOrganization_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrganization_JButtonActionPerformed(evt);
            }
        });

        ManageEmployee_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageEmployee_JButton.setText("Manage Employee");
        ManageEmployee_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmployee_JButtonActionPerformed(evt);
            }
        });

        ManageUser_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageUser_JButton.setText("Manage User");
        ManageUser_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUser_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Title_JLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ManageEmployee_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Enterprise_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Value_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ManageOrganization_JButton)))
                        .addComponent(ManageUser_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Title_JLabel)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enterprise_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Value_JLabel))
                .addGap(20, 20, 20)
                .addComponent(ManageOrganization_JButton)
                .addGap(27, 27, 27)
                .addComponent(ManageEmployee_JButton)
                .addGap(27, 27, 27)
                .addComponent(ManageUser_JButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageUser_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUser_JButtonActionPerformed
        // TODO add your handling code here:
       ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageUser_JButtonActionPerformed

    private void ManageEmployee_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmployee_JButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganisationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageEmployee_JButtonActionPerformed

    private void ManageOrganization_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrganization_JButtonActionPerformed
       
        ManageOrganisationJPanel manageOrganizationJPanel = new ManageOrganisationJPanel(userProcessContainer, enterprise.getOrganisationDirectory(),enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrganization_JButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enterprise_JLabel;
    private javax.swing.JButton ManageEmployee_JButton;
    private javax.swing.JButton ManageOrganization_JButton;
    private javax.swing.JButton ManageUser_JButton;
    private javax.swing.JLabel Title_JLabel;
    private javax.swing.JLabel Value_JLabel;
    // End of variables declaration//GEN-END:variables
    
}
