/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FireRequestRehab;

import Business.WorkQueue.FireRehabRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author janiv
 */
public class ProcessFireRehab_JPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
 private FireRehabRequest fireRehabRequest;

    /**
     * Creates new form ProcessFireRehab_JPanel
     */
    

    ProcessFireRehab_JPanel(JPanel userProcessContainer, FireRehabRequest request) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.fireRehabRequest = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address_JTextField = new javax.swing.JTextField();
        Address_JLabel = new javax.swing.JLabel();
        PhoneNumber_JLabel = new javax.swing.JLabel();
        Message_JLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PhoneNumber_JTextField = new javax.swing.JTextField();
        Message_JTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        Email_JLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        EmailAddress_JTextField = new javax.swing.JTextField();
        Valid2_JLabel = new javax.swing.JLabel();
        Valid3_JLabel = new javax.swing.JLabel();
        Valid_JLabel = new javax.swing.JLabel();
        Valid1_JLabel = new javax.swing.JLabel();
        Reset_JButton = new javax.swing.JButton();

        Address_JTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Address_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Address_JLabel.setText("Address");

        PhoneNumber_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PhoneNumber_JLabel.setText("Phone Number");

        Message_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Message_JLabel.setText("Message");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Availability");

        PhoneNumber_JTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Message_JTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitJButton.setText("Submit Result >>");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        Email_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email_JLabel.setText("Email Addres");

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        EmailAddress_JTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Valid2_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Valid2_JLabel.setToolTipText("");
        Valid2_JLabel.setPreferredSize(new java.awt.Dimension(6, 20));

        Valid3_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Valid3_JLabel.setToolTipText("");
        Valid3_JLabel.setPreferredSize(new java.awt.Dimension(6, 20));
        Valid3_JLabel.setRequestFocusEnabled(false);

        Valid_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Valid_JLabel.setToolTipText("");
        Valid_JLabel.setPreferredSize(new java.awt.Dimension(6, 20));

        Valid1_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Valid1_JLabel.setToolTipText("");
        Valid1_JLabel.setPreferredSize(new java.awt.Dimension(6, 20));

        Reset_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset_JButton.setText("Reset");
        Reset_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Message_JLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Message_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PhoneNumber_JLabel)
                                            .addComponent(Email_JLabel)
                                            .addComponent(Address_JLabel))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PhoneNumber_JTextField)
                                            .addComponent(EmailAddress_JTextField)
                                            .addComponent(Address_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Valid_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Valid3_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Valid2_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Valid1_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitJButton)))
                        .addGap(405, 405, 405))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Reset_JButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reset_JButton)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Message_JLabel)
                            .addComponent(Message_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumber_JLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailAddress_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_JLabel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Address_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address_JLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitJButton)
                            .addComponent(backJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Valid_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Valid1_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Valid2_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Valid3_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        fireRehabRequest.setAvailability(Message_JTextField.getText());
        fireRehabRequest.setPhoneNumber(PhoneNumber_JTextField.getText());
        fireRehabRequest.setEmailAddress(EmailAddress_JTextField.getText());
        fireRehabRequest.setAddress(Address_JTextField.getText());
        fireRehabRequest.setStatus("Completed");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFireRehab_JPanel dwjp = ( ManageFireRehab_JPanel) component;
        dwjp.PopulateFireRehabRequest();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void Reset_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_JButtonActionPerformed
        Message_JTextField.setText("");
        PhoneNumber_JTextField.setText("");
        EmailAddress_JTextField.setText("");
        Address_JTextField.setText("");
    }//GEN-LAST:event_Reset_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_JLabel;
    private javax.swing.JTextField Address_JTextField;
    private javax.swing.JTextField EmailAddress_JTextField;
    private javax.swing.JLabel Email_JLabel;
    private javax.swing.JLabel Message_JLabel;
    private javax.swing.JTextField Message_JTextField;
    private javax.swing.JLabel PhoneNumber_JLabel;
    private javax.swing.JTextField PhoneNumber_JTextField;
    private javax.swing.JButton Reset_JButton;
    private javax.swing.JLabel Valid1_JLabel;
    private javax.swing.JLabel Valid2_JLabel;
    private javax.swing.JLabel Valid3_JLabel;
    private javax.swing.JLabel Valid_JLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
